--------------------------------------------------------
--  File created - Wednesday-September-30-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure Y_SP_LOAD_UNIFIED_MEMBER_X_COPY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "POPHEALTH_ANALYTICS_DEV"."Y_SP_LOAD_UNIFIED_MEMBER_X_COPY" AS

v_record_count NUMBER(20):=0; 
v_start_time DATE;
v_end_time DATE;
v_table_name VARCHAR2(30);
v_category VARCHAR2(20):='UNIFIED X COPY';
v_payer VARCHAR2(100);
v_subpayer VARCHAR2(100);
v_err VARCHAR2(100);
v_msg VARCHAR2(200);
v_rolling_from_dt DATE;
v_rolling_to_dt DATE;
BEGIN

v_payer:='ALL';
v_subpayer:='ALL';
v_record_count:=0;
v_start_time:=sysdate;
v_table_name := 'UNIFIED ALL';

Insert into Y_TABLE_REFRESH(TABLE_NAME,PAYER,CATEGORY,DATE_THROUGH_TYPE,DATE_THROUGH,START_TIME,END_TIME,RECORD_COUNT,RECORD_DIFF,LOAD_DT,status)
            Values(v_table_name,v_subpayer,v_category,'N/A',NULL,v_start_time,NULL,NULL,NULL,NULL,NULL);
COMMIT;

execute immediate 'truncate table X_UNIFIED_MEMBER_VISITS';

insert into X_UNIFIED_MEMBER_VISITS
(PAYER, LOB, MEMBER_ID, MRN, ENCOUNTER_ID, EFFPER, DATE_OF_SERVICE, SOURCE, VISIT_STATUS_TYPE, HISTORICAL_PCP_NPI, HISTORICAL_PCP_TIN, HISTORICAL_PCP_EMP_STATUS, HISTORICAL_PCP_POD, HISTORICAL_PCP_PRACTICE, HISTORICAL_PCP_PROVIDER, HISTORICAL_PROV_PCP_SPC, HISTORICAL_PROV_CMS_PCP_SPC, HISTORICAL_PRAC_EPIC_STATUS, CURRENT_PCP_NPI, CURRENT_PCP_TIN, CURRENT_PCP_EMP_STATUS, CURRENT_PCP_POD, CURRENT_PCP_PRACTICE, CURRENT_PCP_PROVIDER, CURRENT_PROV_PCP_SPC, CURRENT_PROV_CMS_PCP_SPC, CURRENT_PRAC_EPIC_STATUS, SERVICING_PCP_NPI, SERVICING_PCP_TIN, SERVICING_PCP_EMP_STATUS, SERVICING_PCP_POD, SERVICING_PCP_PRACTICE, SERVICING_PCP_PROVIDER, SERVICING_PROV_PCP_SPC, SERVICING_PROV_CMS_PCP_SPC, SERVICING_PRAC_EPIC_STATUS, ATTRIBUTED_AT_VISIT, CURRENTLY_ATTRIBUTED, HIST_SERV_PROV_CHECK, HIST_SERV_PRAC_CHECK, CURRENT_SERV_PROV_CHECK, CURRENT_SERV_PRAC_CHECK, VISIT_WITH_ANY_SPC_PCP, VISIT_WITH_ANY_CMS_SPC_PCP, AWV_INDICATOR, LOAD_DT)
select /*+ parallel(8) */ PAYER, LOB, MEMBER_ID, MRN, ENCOUNTER_ID, EFFPER, DATE_OF_SERVICE, SOURCE, VISIT_STATUS_TYPE, HISTORICAL_PCP_NPI, HISTORICAL_PCP_TIN, HISTORICAL_PCP_EMP_STATUS, HISTORICAL_PCP_POD, HISTORICAL_PCP_PRACTICE, HISTORICAL_PCP_PROVIDER, HISTORICAL_PROV_PCP_SPC, HISTORICAL_PROV_CMS_PCP_SPC, HISTORICAL_PRAC_EPIC_STATUS, CURRENT_PCP_NPI, CURRENT_PCP_TIN, CURRENT_PCP_EMP_STATUS, CURRENT_PCP_POD, CURRENT_PCP_PRACTICE, CURRENT_PCP_PROVIDER, CURRENT_PROV_PCP_SPC, CURRENT_PROV_CMS_PCP_SPC, CURRENT_PRAC_EPIC_STATUS, SERVICING_PCP_NPI, SERVICING_PCP_TIN, SERVICING_PCP_EMP_STATUS, SERVICING_PCP_POD, SERVICING_PCP_PRACTICE, SERVICING_PCP_PROVIDER, SERVICING_PROV_PCP_SPC, SERVICING_PROV_CMS_PCP_SPC, SERVICING_PRAC_EPIC_STATUS, ATTRIBUTED_AT_VISIT, CURRENTLY_ATTRIBUTED, HIST_SERV_PROV_CHECK, HIST_SERV_PRAC_CHECK, CURRENT_SERV_PROV_CHECK, CURRENT_SERV_PRAC_CHECK, VISIT_WITH_ANY_SPC_PCP, VISIT_WITH_ANY_CMS_SPC_PCP, AWV_INDICATOR, LOAD_DT
from Y_UNIFIED_MEMBER_VISITS;
commit;

execute immediate 'truncate table X_PATIENT_SEEN_VISITS_ALL';

insert into X_PATIENT_SEEN_VISITS_ALL
(PAYER, LOB, MEMBER_ID, MRN, ENCOUNTER_ID, EFFPER, DATE_OF_SERVICE, SOURCE, VISIT_STATUS_TYPE, HISTORICAL_PCP_NPI, HISTORICAL_PCP_TIN, HISTORICAL_PCP_EMP_STATUS, HISTORICAL_PCP_POD, HISTORICAL_PCP_PRACTICE, HISTORICAL_PCP_PROVIDER, HISTORICAL_PROV_PCP_SPC, HISTORICAL_PROV_CMS_PCP_SPC, HISTORICAL_PRAC_EPIC_STATUS, CURRENT_PCP_NPI, CURRENT_PCP_TIN, CURRENT_PCP_EMP_STATUS, CURRENT_PCP_POD, CURRENT_PCP_PRACTICE, CURRENT_PCP_PROVIDER, CURRENT_PROV_PCP_SPC, CURRENT_PROV_CMS_PCP_SPC, CURRENT_PRAC_EPIC_STATUS, SERVICING_PCP_NPI, SERVICING_PCP_TIN, SERVICING_PCP_EMP_STATUS, SERVICING_PCP_POD, SERVICING_PCP_PRACTICE, SERVICING_PCP_PROVIDER, SERVICING_PROV_PCP_SPC, SERVICING_PROV_CMS_PCP_SPC, SERVICING_PRAC_EPIC_STATUS, ATTRIBUTED_AT_VISIT, CURRENTLY_ATTRIBUTED, HIST_SERV_PROV_CHECK, HIST_SERV_PRAC_CHECK, CURRENT_SERV_PROV_CHECK, CURRENT_SERV_PRAC_CHECK, VISIT_WITH_ANY_SPC_PCP, VISIT_WITH_ANY_CMS_SPC_PCP, AWV_INDICATOR, LOAD_DT, EFFYEAR, GROUPER_NAME, DEPARTMENT_NAME, ENC_TYPE_C, ENC_TYPE_POS, PROC_CODE, PROC_CODE_DESC, PROV_TITLE, PROV_TITLE_ID, PAYER_NOT_CHGD, CREATE_DT, PROV_NAME, APPT_STATUS, ENC_CLOSED_YN, PC_VISIT_CMPLT_CLOSE_YN, PC_VISIT_LOS_CODE_YN, PC_VISIT_PROV_TYPE_YN, PC_VISIT_GROUPER_YN, PC_VISIT_ALL_MATCH_YN)
select /*+ parallel(8) */ PAYER, LOB, MEMBER_ID, MRN, ENCOUNTER_ID, EFFPER, DATE_OF_SERVICE, SOURCE, VISIT_STATUS_TYPE, HISTORICAL_PCP_NPI, HISTORICAL_PCP_TIN, HISTORICAL_PCP_EMP_STATUS, HISTORICAL_PCP_POD, HISTORICAL_PCP_PRACTICE, HISTORICAL_PCP_PROVIDER, HISTORICAL_PROV_PCP_SPC, HISTORICAL_PROV_CMS_PCP_SPC, HISTORICAL_PRAC_EPIC_STATUS, CURRENT_PCP_NPI, CURRENT_PCP_TIN, CURRENT_PCP_EMP_STATUS, CURRENT_PCP_POD, CURRENT_PCP_PRACTICE, CURRENT_PCP_PROVIDER, CURRENT_PROV_PCP_SPC, CURRENT_PROV_CMS_PCP_SPC, CURRENT_PRAC_EPIC_STATUS, SERVICING_PCP_NPI, SERVICING_PCP_TIN, SERVICING_PCP_EMP_STATUS, SERVICING_PCP_POD, SERVICING_PCP_PRACTICE, SERVICING_PCP_PROVIDER, SERVICING_PROV_PCP_SPC, SERVICING_PROV_CMS_PCP_SPC, SERVICING_PRAC_EPIC_STATUS, ATTRIBUTED_AT_VISIT, CURRENTLY_ATTRIBUTED, HIST_SERV_PROV_CHECK, HIST_SERV_PRAC_CHECK, CURRENT_SERV_PROV_CHECK, CURRENT_SERV_PRAC_CHECK, VISIT_WITH_ANY_SPC_PCP, VISIT_WITH_ANY_CMS_SPC_PCP, AWV_INDICATOR, LOAD_DT, EFFYEAR, GROUPER_NAME, DEPARTMENT_NAME, ENC_TYPE_C, ENC_TYPE_POS, PROC_CODE, PROC_CODE_DESC, PROV_TITLE, PROV_TITLE_ID, PAYER_NOT_CHGD, CREATE_DT, PROV_NAME, APPT_STATUS, ENC_CLOSED_YN, PC_VISIT_CMPLT_CLOSE_YN, PC_VISIT_LOS_CODE_YN, PC_VISIT_PROV_TYPE_YN, PC_VISIT_GROUPER_YN, PC_VISIT_ALL_MATCH_YN
from Y_PATIENT_SEEN_VISITS_ALL;
commit;

execute immediate 'truncate table X_PATIENT_SEEN_VISITS_DATA_MART';

insert into X_PATIENT_SEEN_VISITS_DATA_MART
(PAYER, LOB, MEMBER_ID, PRI_MRN, ENCOUNTER_ID, EFFPER, DATE_OF_SERVICE, SOURCE, VISIT_STATUS_TYPE, SERVICING_PCP_NPI, SERVICING_PCP_TIN, SERVICING_PCP_EMP_STATUS, SERVICING_PCP_POD, SERVICING_PCP_PRACTICE, SERVICING_PCP_PROVIDER, EFFMONTH, EFFYEAR, PC_GROUPER_NAME, EPIC_DEPT, ENC_TYPE_C, ENC_TYPE_POS, PROC_CODE, PROC_CODE_DESC, PROV_TITLE, PROV_TITLE_ID, PRAC_EMP_STATUS, PCP_EMP_STATUS, CRNT_PYR, VBC_FLAG, DEATH_DT, PAYER_EFFPER_NPI, PAYER_EFFPER_LVL4_PRACTICE, PAYER_EFFPER_FULL_NAME, PAYER_EFFPER_POD, PAYER_EFFPER_PRAC_EMP_STATUS, PAYER_CURRENT_NPI, PAYER_CURRENT_LVL4_PRACTICE, PAYER_CURRENT_FULL_NAME, PAYER_CURRENT_POD, PAYER_CURRENT_PRAC_EMP_STATUS, EPIC_NPI, EPIC_LVL4_PRACTICE, EPIC_FULL_NAME, EPIC_POD, EPIC_PRAC_EMP_STATUS, EXCLUDED_EPIC_PROV_TYPE, EXCLUDED_EPIC_ENC_TYPE, EXCLUDED_PROC_CODE, EXCLUDED_ANY_REASON, COMPLETED_VISIT_YN, SCHEDULED_VISIT_YN, SCHED_VISIT_FUTURE_YN, SCHEDULED_WI_180DAYS_YN, PAYER_CURRENT_MATCH, PAYER_EFFPER_MATCH, EPIC_MATCH, PC_GROUPER_MATCH, RYAN_MATCH, ONE_MED_MATCH, ANY_MATCH, HISTORIC_DEF_MATCH, SERVICING_PROV_PCP_SPC, SERVICING_PROV_CMS_PCP_SPC, SERVICING_PRAC_EPIC_STATUS, HISTORICAL_PCP_NPI, HISTORICAL_PCP_TIN, HISTORICAL_PCP_EMP_STATUS, HISTORICAL_PCP_POD, HISTORICAL_PCP_PRACTICE, HISTORICAL_PCP_PROVIDER, HISTORICAL_PROV_PCP_SPC, HISTORICAL_PROV_CMS_PCP_SPC, HISTORICAL_PRAC_EPIC_STATUS, CURRENT_PCP_NPI, CURRENT_PCP_TIN, CURRENT_PCP_EMP_STATUS, CURRENT_PCP_POD, CURRENT_PCP_PRACTICE, CURRENT_PCP_PROVIDER, CURRENT_PROV_PCP_SPC, CURRENT_PROV_CMS_PCP_SPC, CURRENT_PRAC_EPIC_STATUS, ATTRIBUTED_AT_VISIT, CURRENTLY_ATTRIBUTED, HIST_SERV_PROV_CHECK, HIST_SERV_PRAC_CHECK, CURRENT_SERV_PROV_CHECK, CURRENT_SERV_PRAC_CHECK, VISIT_WITH_ANY_SPC_PCP, VISIT_WITH_ANY_CMS_SPC_PCP, AWV_INDICATOR, S0_ENCOUNTER_TABLE, S0_ENCOUNTER_TABLE_UPDATE, S1_ENCOUNTER_TABLE, S1_ENCOUNTER_TABLE_UPDATE, ORIG_RN, DATA_UPDATE_DT, ENC_CLOSED_YN, PC_VISIT_ALL_MATCH_YN, PC_VISIT_CMPLT_CLOSE_YN, PC_VISIT_GROUPER_YN, PC_VISIT_LOS_CODE_YN, PC_VISIT_PROV_TYPE_YN, DOS_NPI_RN, ENC_RN)
select /*+ parallel(8) */ PAYER, LOB, MEMBER_ID, PRI_MRN, ENCOUNTER_ID, EFFPER, DATE_OF_SERVICE, SOURCE, VISIT_STATUS_TYPE, SERVICING_PCP_NPI, SERVICING_PCP_TIN, SERVICING_PCP_EMP_STATUS, SERVICING_PCP_POD, SERVICING_PCP_PRACTICE, SERVICING_PCP_PROVIDER, EFFMONTH, EFFYEAR, PC_GROUPER_NAME, EPIC_DEPT, ENC_TYPE_C, ENC_TYPE_POS, PROC_CODE, PROC_CODE_DESC, PROV_TITLE, PROV_TITLE_ID, PRAC_EMP_STATUS, PCP_EMP_STATUS, CRNT_PYR, VBC_FLAG, DEATH_DT, PAYER_EFFPER_NPI, PAYER_EFFPER_LVL4_PRACTICE, PAYER_EFFPER_FULL_NAME, PAYER_EFFPER_POD, PAYER_EFFPER_PRAC_EMP_STATUS, PAYER_CURRENT_NPI, PAYER_CURRENT_LVL4_PRACTICE, PAYER_CURRENT_FULL_NAME, PAYER_CURRENT_POD, PAYER_CURRENT_PRAC_EMP_STATUS, EPIC_NPI, EPIC_LVL4_PRACTICE, EPIC_FULL_NAME, EPIC_POD, EPIC_PRAC_EMP_STATUS, EXCLUDED_EPIC_PROV_TYPE, EXCLUDED_EPIC_ENC_TYPE, EXCLUDED_PROC_CODE, EXCLUDED_ANY_REASON, COMPLETED_VISIT_YN, SCHEDULED_VISIT_YN, SCHED_VISIT_FUTURE_YN, SCHEDULED_WI_180DAYS_YN, PAYER_CURRENT_MATCH, PAYER_EFFPER_MATCH, EPIC_MATCH, PC_GROUPER_MATCH, RYAN_MATCH, ONE_MED_MATCH, ANY_MATCH, HISTORIC_DEF_MATCH, SERVICING_PROV_PCP_SPC, SERVICING_PROV_CMS_PCP_SPC, SERVICING_PRAC_EPIC_STATUS, HISTORICAL_PCP_NPI, HISTORICAL_PCP_TIN, HISTORICAL_PCP_EMP_STATUS, HISTORICAL_PCP_POD, HISTORICAL_PCP_PRACTICE, HISTORICAL_PCP_PROVIDER, HISTORICAL_PROV_PCP_SPC, HISTORICAL_PROV_CMS_PCP_SPC, HISTORICAL_PRAC_EPIC_STATUS, CURRENT_PCP_NPI, CURRENT_PCP_TIN, CURRENT_PCP_EMP_STATUS, CURRENT_PCP_POD, CURRENT_PCP_PRACTICE, CURRENT_PCP_PROVIDER, CURRENT_PROV_PCP_SPC, CURRENT_PROV_CMS_PCP_SPC, CURRENT_PRAC_EPIC_STATUS, ATTRIBUTED_AT_VISIT, CURRENTLY_ATTRIBUTED, HIST_SERV_PROV_CHECK, HIST_SERV_PRAC_CHECK, CURRENT_SERV_PROV_CHECK, CURRENT_SERV_PRAC_CHECK, VISIT_WITH_ANY_SPC_PCP, VISIT_WITH_ANY_CMS_SPC_PCP, AWV_INDICATOR, S0_ENCOUNTER_TABLE, S0_ENCOUNTER_TABLE_UPDATE, S1_ENCOUNTER_TABLE, S1_ENCOUNTER_TABLE_UPDATE, ORIG_RN, DATA_UPDATE_DT, ENC_CLOSED_YN, PC_VISIT_ALL_MATCH_YN, PC_VISIT_CMPLT_CLOSE_YN, PC_VISIT_GROUPER_YN, PC_VISIT_LOS_CODE_YN, PC_VISIT_PROV_TYPE_YN, DOS_NPI_RN, ENC_RN
from Y_PATIENT_SEEN_VISITS_DATA_MART;
commit;

v_end_time:=sysdate;

UPDATE  Y_TABLE_REFRESH SET 
END_TIME=v_end_time,
RECORD_COUNT=v_record_count,
load_dt=trunc(sysdate),
status = 'Completed'
WHERE TABLE_NAME=v_table_name AND PAYER=v_subpayer  AND START_TIME = v_start_time;
COMMIT;

EXCEPTION
WHEN OTHERS THEN
    v_err:= SQLCODE;
    v_msg:= SUBSTR(SQLERRM, 1, 200);
    INSERT INTO y_table_err_log (TABLE_NAME,PAYER,category,START_TIME,ERROR_TIME,ERROR_CODE,ERROR_MSG,LOAD_DT,REPROCESSED,REPROCESSED_DT) VALUES (v_table_name,v_subpayer,v_category,v_start_time,SYSDATE,v_err,v_msg,TRUNC(SYSDATE),'N',NULL);
    COMMIT;
    UPDATE  y_TABLE_REFRESH SET END_TIME = SYSDATE,status = 'Failed',load_dt=TRUNC(SYSDATE) WHERE TABLE_NAME=v_table_name AND PAYER=v_subpayer  AND START_TIME = v_start_time;
    COMMIT;

END;

/
